FROM ubuntu:20.04

RUN apt-get update -y && apt-get install -y python3-pip python3-dev git gcc dos2unix g++

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

RUN pip3 install pytest==7.0.1

COPY . /app


CMD ["python3", "-m", "pytest"]